//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.TUPA6Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TUPA6Reference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetEmployeeMetaDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeMetaData", ReplyAction="*")]
        WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponse GetEmployeeMetaData(WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponse> GetEmployeeMetaDataAsync(WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContentFromTable", ReplyAction="*")]
        WindowsClient.TUPA6Reference.GetContentFromTableResponse GetContentFromTable(WindowsClient.TUPA6Reference.GetContentFromTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContentFromTable", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetContentFromTableResponse> GetContentFromTableAsync(WindowsClient.TUPA6Reference.GetContentFromTableRequest request);
        
        // CODEGEN: Generating message contract since element name InformationAboutRelativesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformationAboutRelatives", ReplyAction="*")]
        WindowsClient.TUPA6Reference.InformationAboutRelativesResponse InformationAboutRelatives(WindowsClient.TUPA6Reference.InformationAboutRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformationAboutRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.InformationAboutRelativesResponse> InformationAboutRelativesAsync(WindowsClient.TUPA6Reference.InformationAboutRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name FindSickEmployeesFrom2004Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindSickEmployeesFrom2004", ReplyAction="*")]
        WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Response FindSickEmployeesFrom2004(WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindSickEmployeesFrom2004", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Response> FindSickEmployeesFrom2004Async(WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request request);
        
        // CODEGEN: Generating message contract since element name FindMostAbsentEmployeeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindMostAbsentEmployee", ReplyAction="*")]
        WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponse FindMostAbsentEmployee(WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindMostAbsentEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponse> FindMostAbsentEmployeeAsync(WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTablesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTables", ReplyAction="*")]
        WindowsClient.TUPA6Reference.GetAllTablesResponse GetAllTables(WindowsClient.TUPA6Reference.GetAllTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTables", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllTablesResponse> GetAllTablesAsync(WindowsClient.TUPA6Reference.GetAllTablesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllKeysResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        WindowsClient.TUPA6Reference.GetAllKeysResponse GetAllKeys(WindowsClient.TUPA6Reference.GetAllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllKeysResponse> GetAllKeysAsync(WindowsClient.TUPA6Reference.GetAllKeysRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllIndexesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        WindowsClient.TUPA6Reference.GetAllIndexesResponse GetAllIndexes(WindowsClient.TUPA6Reference.GetAllIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllIndexesResponse> GetAllIndexesAsync(WindowsClient.TUPA6Reference.GetAllIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        WindowsClient.TUPA6Reference.GetAllConstraintsResponse GetAllConstraints(WindowsClient.TUPA6Reference.GetAllConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllConstraintsResponse> GetAllConstraintsAsync(WindowsClient.TUPA6Reference.GetAllConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllEmployeeColumnsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployeeColumns", ReplyAction="*")]
        WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponse GetAllEmployeeColumns(WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployeeColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponse> GetAllEmployeeColumnsAsync(WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeMetaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeMetaData", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequestBody Body;
        
        public GetEmployeeMetaDataRequest() {
        }
        
        public GetEmployeeMetaDataRequest(WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeMetaDataRequestBody {
        
        public GetEmployeeMetaDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeMetaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeMetaDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponseBody Body;
        
        public GetEmployeeMetaDataResponse() {
        }
        
        public GetEmployeeMetaDataResponse(WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeMetaDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfString> GetEmployeeMetaDataResult;
        
        public GetEmployeeMetaDataResponseBody() {
        }
        
        public GetEmployeeMetaDataResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfString> GetEmployeeMetaDataResult) {
            this.GetEmployeeMetaDataResult = GetEmployeeMetaDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentFromTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentFromTable", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetContentFromTableRequestBody Body;
        
        public GetContentFromTableRequest() {
        }
        
        public GetContentFromTableRequest(WindowsClient.TUPA6Reference.GetContentFromTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContentFromTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public GetContentFromTableRequestBody() {
        }
        
        public GetContentFromTableRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentFromTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentFromTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetContentFromTableResponseBody Body;
        
        public GetContentFromTableResponse() {
        }
        
        public GetContentFromTableResponse(WindowsClient.TUPA6Reference.GetContentFromTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContentFromTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetContentFromTableResult;
        
        public GetContentFromTableResponseBody() {
        }
        
        public GetContentFromTableResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetContentFromTableResult) {
            this.GetContentFromTableResult = GetContentFromTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformationAboutRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformationAboutRelatives", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.InformationAboutRelativesRequestBody Body;
        
        public InformationAboutRelativesRequest() {
        }
        
        public InformationAboutRelativesRequest(WindowsClient.TUPA6Reference.InformationAboutRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InformationAboutRelativesRequestBody {
        
        public InformationAboutRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformationAboutRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformationAboutRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.InformationAboutRelativesResponseBody Body;
        
        public InformationAboutRelativesResponse() {
        }
        
        public InformationAboutRelativesResponse(WindowsClient.TUPA6Reference.InformationAboutRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InformationAboutRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> InformationAboutRelativesResult;
        
        public InformationAboutRelativesResponseBody() {
        }
        
        public InformationAboutRelativesResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> InformationAboutRelativesResult) {
            this.InformationAboutRelativesResult = InformationAboutRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindSickEmployeesFrom2004Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindSickEmployeesFrom2004", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004RequestBody Body;
        
        public FindSickEmployeesFrom2004Request() {
        }
        
        public FindSickEmployeesFrom2004Request(WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindSickEmployeesFrom2004RequestBody {
        
        public FindSickEmployeesFrom2004RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindSickEmployeesFrom2004Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindSickEmployeesFrom2004Response", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004ResponseBody Body;
        
        public FindSickEmployeesFrom2004Response() {
        }
        
        public FindSickEmployeesFrom2004Response(WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindSickEmployeesFrom2004ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> FindSickEmployeesFrom2004Result;
        
        public FindSickEmployeesFrom2004ResponseBody() {
        }
        
        public FindSickEmployeesFrom2004ResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> FindSickEmployeesFrom2004Result) {
            this.FindSickEmployeesFrom2004Result = FindSickEmployeesFrom2004Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindMostAbsentEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindMostAbsentEmployee", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequestBody Body;
        
        public FindMostAbsentEmployeeRequest() {
        }
        
        public FindMostAbsentEmployeeRequest(WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindMostAbsentEmployeeRequestBody {
        
        public FindMostAbsentEmployeeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindMostAbsentEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindMostAbsentEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponseBody Body;
        
        public FindMostAbsentEmployeeResponse() {
        }
        
        public FindMostAbsentEmployeeResponse(WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindMostAbsentEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> FindMostAbsentEmployeeResult;
        
        public FindMostAbsentEmployeeResponseBody() {
        }
        
        public FindMostAbsentEmployeeResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> FindMostAbsentEmployeeResult) {
            this.FindMostAbsentEmployeeResult = FindMostAbsentEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTables", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllTablesRequestBody Body;
        
        public GetAllTablesRequest() {
        }
        
        public GetAllTablesRequest(WindowsClient.TUPA6Reference.GetAllTablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTablesRequestBody {
        
        public GetAllTablesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllTablesResponseBody Body;
        
        public GetAllTablesResponse() {
        }
        
        public GetAllTablesResponse(WindowsClient.TUPA6Reference.GetAllTablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllTablesResult;
        
        public GetAllTablesResponseBody() {
        }
        
        public GetAllTablesResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllTablesResult) {
            this.GetAllTablesResult = GetAllTablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeys", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllKeysRequestBody Body;
        
        public GetAllKeysRequest() {
        }
        
        public GetAllKeysRequest(WindowsClient.TUPA6Reference.GetAllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKeysRequestBody {
        
        public GetAllKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllKeysResponseBody Body;
        
        public GetAllKeysResponse() {
        }
        
        public GetAllKeysResponse(WindowsClient.TUPA6Reference.GetAllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllKeysResult;
        
        public GetAllKeysResponseBody() {
        }
        
        public GetAllKeysResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllKeysResult) {
            this.GetAllKeysResult = GetAllKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexes", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllIndexesRequestBody Body;
        
        public GetAllIndexesRequest() {
        }
        
        public GetAllIndexesRequest(WindowsClient.TUPA6Reference.GetAllIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllIndexesRequestBody {
        
        public GetAllIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllIndexesResponseBody Body;
        
        public GetAllIndexesResponse() {
        }
        
        public GetAllIndexesResponse(WindowsClient.TUPA6Reference.GetAllIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllIndexesResult;
        
        public GetAllIndexesResponseBody() {
        }
        
        public GetAllIndexesResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllIndexesResult) {
            this.GetAllIndexesResult = GetAllIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraints", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllConstraintsRequestBody Body;
        
        public GetAllConstraintsRequest() {
        }
        
        public GetAllConstraintsRequest(WindowsClient.TUPA6Reference.GetAllConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllConstraintsRequestBody {
        
        public GetAllConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllConstraintsResponseBody Body;
        
        public GetAllConstraintsResponse() {
        }
        
        public GetAllConstraintsResponse(WindowsClient.TUPA6Reference.GetAllConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllConstraintsResult;
        
        public GetAllConstraintsResponseBody() {
        }
        
        public GetAllConstraintsResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllConstraintsResult) {
            this.GetAllConstraintsResult = GetAllConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeeColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeeColumns", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequestBody Body;
        
        public GetAllEmployeeColumnsRequest() {
        }
        
        public GetAllEmployeeColumnsRequest(WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEmployeeColumnsRequestBody {
        
        public GetAllEmployeeColumnsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeeColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeeColumnsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponseBody Body;
        
        public GetAllEmployeeColumnsResponse() {
        }
        
        public GetAllEmployeeColumnsResponse(WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEmployeeColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllEmployeeColumnsResult;
        
        public GetAllEmployeeColumnsResponseBody() {
        }
        
        public GetAllEmployeeColumnsResponseBody(System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllEmployeeColumnsResult) {
            this.GetAllEmployeeColumnsResult = GetAllEmployeeColumnsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsClient.TUPA6Reference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsClient.TUPA6Reference.WebService1Soap>, WindowsClient.TUPA6Reference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponse WindowsClient.TUPA6Reference.WebService1Soap.GetEmployeeMetaData(WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest request) {
            return base.Channel.GetEmployeeMetaData(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfString> GetEmployeeMetaData() {
            WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest inValue = new WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequestBody();
            WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetEmployeeMetaData(inValue);
            return retVal.Body.GetEmployeeMetaDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponse> WindowsClient.TUPA6Reference.WebService1Soap.GetEmployeeMetaDataAsync(WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest request) {
            return base.Channel.GetEmployeeMetaDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetEmployeeMetaDataResponse> GetEmployeeMetaDataAsync() {
            WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest inValue = new WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetEmployeeMetaDataRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetEmployeeMetaDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.GetContentFromTableResponse WindowsClient.TUPA6Reference.WebService1Soap.GetContentFromTable(WindowsClient.TUPA6Reference.GetContentFromTableRequest request) {
            return base.Channel.GetContentFromTable(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetContentFromTable(string tableName) {
            WindowsClient.TUPA6Reference.GetContentFromTableRequest inValue = new WindowsClient.TUPA6Reference.GetContentFromTableRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetContentFromTableRequestBody();
            inValue.Body.tableName = tableName;
            WindowsClient.TUPA6Reference.GetContentFromTableResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetContentFromTable(inValue);
            return retVal.Body.GetContentFromTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetContentFromTableResponse> WindowsClient.TUPA6Reference.WebService1Soap.GetContentFromTableAsync(WindowsClient.TUPA6Reference.GetContentFromTableRequest request) {
            return base.Channel.GetContentFromTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetContentFromTableResponse> GetContentFromTableAsync(string tableName) {
            WindowsClient.TUPA6Reference.GetContentFromTableRequest inValue = new WindowsClient.TUPA6Reference.GetContentFromTableRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetContentFromTableRequestBody();
            inValue.Body.tableName = tableName;
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetContentFromTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.InformationAboutRelativesResponse WindowsClient.TUPA6Reference.WebService1Soap.InformationAboutRelatives(WindowsClient.TUPA6Reference.InformationAboutRelativesRequest request) {
            return base.Channel.InformationAboutRelatives(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> InformationAboutRelatives() {
            WindowsClient.TUPA6Reference.InformationAboutRelativesRequest inValue = new WindowsClient.TUPA6Reference.InformationAboutRelativesRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.InformationAboutRelativesRequestBody();
            WindowsClient.TUPA6Reference.InformationAboutRelativesResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).InformationAboutRelatives(inValue);
            return retVal.Body.InformationAboutRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.InformationAboutRelativesResponse> WindowsClient.TUPA6Reference.WebService1Soap.InformationAboutRelativesAsync(WindowsClient.TUPA6Reference.InformationAboutRelativesRequest request) {
            return base.Channel.InformationAboutRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.InformationAboutRelativesResponse> InformationAboutRelativesAsync() {
            WindowsClient.TUPA6Reference.InformationAboutRelativesRequest inValue = new WindowsClient.TUPA6Reference.InformationAboutRelativesRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.InformationAboutRelativesRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).InformationAboutRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Response WindowsClient.TUPA6Reference.WebService1Soap.FindSickEmployeesFrom2004(WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request request) {
            return base.Channel.FindSickEmployeesFrom2004(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> FindSickEmployeesFrom2004() {
            WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request inValue = new WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request();
            inValue.Body = new WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004RequestBody();
            WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Response retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).FindSickEmployeesFrom2004(inValue);
            return retVal.Body.FindSickEmployeesFrom2004Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Response> WindowsClient.TUPA6Reference.WebService1Soap.FindSickEmployeesFrom2004Async(WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request request) {
            return base.Channel.FindSickEmployeesFrom2004Async(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Response> FindSickEmployeesFrom2004Async() {
            WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request inValue = new WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004Request();
            inValue.Body = new WindowsClient.TUPA6Reference.FindSickEmployeesFrom2004RequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).FindSickEmployeesFrom2004Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponse WindowsClient.TUPA6Reference.WebService1Soap.FindMostAbsentEmployee(WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest request) {
            return base.Channel.FindMostAbsentEmployee(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> FindMostAbsentEmployee() {
            WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest inValue = new WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequestBody();
            WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).FindMostAbsentEmployee(inValue);
            return retVal.Body.FindMostAbsentEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponse> WindowsClient.TUPA6Reference.WebService1Soap.FindMostAbsentEmployeeAsync(WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest request) {
            return base.Channel.FindMostAbsentEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.FindMostAbsentEmployeeResponse> FindMostAbsentEmployeeAsync() {
            WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest inValue = new WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.FindMostAbsentEmployeeRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).FindMostAbsentEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.GetAllTablesResponse WindowsClient.TUPA6Reference.WebService1Soap.GetAllTables(WindowsClient.TUPA6Reference.GetAllTablesRequest request) {
            return base.Channel.GetAllTables(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllTables() {
            WindowsClient.TUPA6Reference.GetAllTablesRequest inValue = new WindowsClient.TUPA6Reference.GetAllTablesRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllTablesRequestBody();
            WindowsClient.TUPA6Reference.GetAllTablesResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllTables(inValue);
            return retVal.Body.GetAllTablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllTablesResponse> WindowsClient.TUPA6Reference.WebService1Soap.GetAllTablesAsync(WindowsClient.TUPA6Reference.GetAllTablesRequest request) {
            return base.Channel.GetAllTablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllTablesResponse> GetAllTablesAsync() {
            WindowsClient.TUPA6Reference.GetAllTablesRequest inValue = new WindowsClient.TUPA6Reference.GetAllTablesRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllTablesRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllTablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.GetAllKeysResponse WindowsClient.TUPA6Reference.WebService1Soap.GetAllKeys(WindowsClient.TUPA6Reference.GetAllKeysRequest request) {
            return base.Channel.GetAllKeys(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllKeys() {
            WindowsClient.TUPA6Reference.GetAllKeysRequest inValue = new WindowsClient.TUPA6Reference.GetAllKeysRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllKeysRequestBody();
            WindowsClient.TUPA6Reference.GetAllKeysResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllKeys(inValue);
            return retVal.Body.GetAllKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllKeysResponse> WindowsClient.TUPA6Reference.WebService1Soap.GetAllKeysAsync(WindowsClient.TUPA6Reference.GetAllKeysRequest request) {
            return base.Channel.GetAllKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllKeysResponse> GetAllKeysAsync() {
            WindowsClient.TUPA6Reference.GetAllKeysRequest inValue = new WindowsClient.TUPA6Reference.GetAllKeysRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllKeysRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.GetAllIndexesResponse WindowsClient.TUPA6Reference.WebService1Soap.GetAllIndexes(WindowsClient.TUPA6Reference.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexes(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllIndexes() {
            WindowsClient.TUPA6Reference.GetAllIndexesRequest inValue = new WindowsClient.TUPA6Reference.GetAllIndexesRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllIndexesRequestBody();
            WindowsClient.TUPA6Reference.GetAllIndexesResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllIndexes(inValue);
            return retVal.Body.GetAllIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllIndexesResponse> WindowsClient.TUPA6Reference.WebService1Soap.GetAllIndexesAsync(WindowsClient.TUPA6Reference.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllIndexesResponse> GetAllIndexesAsync() {
            WindowsClient.TUPA6Reference.GetAllIndexesRequest inValue = new WindowsClient.TUPA6Reference.GetAllIndexesRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllIndexesRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.GetAllConstraintsResponse WindowsClient.TUPA6Reference.WebService1Soap.GetAllConstraints(WindowsClient.TUPA6Reference.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraints(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllConstraints() {
            WindowsClient.TUPA6Reference.GetAllConstraintsRequest inValue = new WindowsClient.TUPA6Reference.GetAllConstraintsRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllConstraintsRequestBody();
            WindowsClient.TUPA6Reference.GetAllConstraintsResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllConstraints(inValue);
            return retVal.Body.GetAllConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllConstraintsResponse> WindowsClient.TUPA6Reference.WebService1Soap.GetAllConstraintsAsync(WindowsClient.TUPA6Reference.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllConstraintsResponse> GetAllConstraintsAsync() {
            WindowsClient.TUPA6Reference.GetAllConstraintsRequest inValue = new WindowsClient.TUPA6Reference.GetAllConstraintsRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllConstraintsRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponse WindowsClient.TUPA6Reference.WebService1Soap.GetAllEmployeeColumns(WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest request) {
            return base.Channel.GetAllEmployeeColumns(request);
        }
        
        public System.Collections.Generic.List<WindowsClient.TUPA6Reference.ArrayOfAnyType> GetAllEmployeeColumns() {
            WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest inValue = new WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequestBody();
            WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponse retVal = ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllEmployeeColumns(inValue);
            return retVal.Body.GetAllEmployeeColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponse> WindowsClient.TUPA6Reference.WebService1Soap.GetAllEmployeeColumnsAsync(WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest request) {
            return base.Channel.GetAllEmployeeColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.TUPA6Reference.GetAllEmployeeColumnsResponse> GetAllEmployeeColumnsAsync() {
            WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest inValue = new WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequest();
            inValue.Body = new WindowsClient.TUPA6Reference.GetAllEmployeeColumnsRequestBody();
            return ((WindowsClient.TUPA6Reference.WebService1Soap)(this)).GetAllEmployeeColumnsAsync(inValue);
        }
    }
}
