//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppDebug.TUPA6Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TUPA6Reference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetEmployeeMetaDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeMetaData", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponse GetEmployeeMetaData(ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponse> GetEmployeeMetaDataAsync(ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContentFromTable", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponse GetContentFromTable(ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContentFromTable", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponse> GetContentFromTableAsync(ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest request);
        
        // CODEGEN: Generating message contract since element name InformationAboutRelativesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformationAboutRelatives", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponse InformationAboutRelatives(ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformationAboutRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponse> InformationAboutRelativesAsync(ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name FindSickEmployeesFrom2004Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindSickEmployeesFrom2004", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Response FindSickEmployeesFrom2004(ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindSickEmployeesFrom2004", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Response> FindSickEmployeesFrom2004Async(ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request request);
        
        // CODEGEN: Generating message contract since element name FindMostAbsentEmployeeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindMostAbsentEmployee", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponse FindMostAbsentEmployee(ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindMostAbsentEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponse> FindMostAbsentEmployeeAsync(ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTablesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTables", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.GetAllTablesResponse GetAllTables(ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTables", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllTablesResponse> GetAllTablesAsync(ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllKeysResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.GetAllKeysResponse GetAllKeys(ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllKeysResponse> GetAllKeysAsync(ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllIndexesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponse GetAllIndexes(ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponse> GetAllIndexesAsync(ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponse GetAllConstraints(ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponse> GetAllConstraintsAsync(ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllEmployeeColumnsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployeeColumns", ReplyAction="*")]
        ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponse GetAllEmployeeColumns(ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployeeColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponse> GetAllEmployeeColumnsAsync(ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeMetaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeMetaData", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequestBody Body;
        
        public GetEmployeeMetaDataRequest() {
        }
        
        public GetEmployeeMetaDataRequest(ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeMetaDataRequestBody {
        
        public GetEmployeeMetaDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeMetaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeMetaDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponseBody Body;
        
        public GetEmployeeMetaDataResponse() {
        }
        
        public GetEmployeeMetaDataResponse(ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeMetaDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfString[] GetEmployeeMetaDataResult;
        
        public GetEmployeeMetaDataResponseBody() {
        }
        
        public GetEmployeeMetaDataResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfString[] GetEmployeeMetaDataResult) {
            this.GetEmployeeMetaDataResult = GetEmployeeMetaDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentFromTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentFromTable", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequestBody Body;
        
        public GetContentFromTableRequest() {
        }
        
        public GetContentFromTableRequest(ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContentFromTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public GetContentFromTableRequestBody() {
        }
        
        public GetContentFromTableRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentFromTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentFromTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponseBody Body;
        
        public GetContentFromTableResponse() {
        }
        
        public GetContentFromTableResponse(ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContentFromTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetContentFromTableResult;
        
        public GetContentFromTableResponseBody() {
        }
        
        public GetContentFromTableResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetContentFromTableResult) {
            this.GetContentFromTableResult = GetContentFromTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformationAboutRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformationAboutRelatives", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequestBody Body;
        
        public InformationAboutRelativesRequest() {
        }
        
        public InformationAboutRelativesRequest(ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InformationAboutRelativesRequestBody {
        
        public InformationAboutRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformationAboutRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformationAboutRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponseBody Body;
        
        public InformationAboutRelativesResponse() {
        }
        
        public InformationAboutRelativesResponse(ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InformationAboutRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] InformationAboutRelativesResult;
        
        public InformationAboutRelativesResponseBody() {
        }
        
        public InformationAboutRelativesResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] InformationAboutRelativesResult) {
            this.InformationAboutRelativesResult = InformationAboutRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindSickEmployeesFrom2004Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindSickEmployeesFrom2004", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004RequestBody Body;
        
        public FindSickEmployeesFrom2004Request() {
        }
        
        public FindSickEmployeesFrom2004Request(ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindSickEmployeesFrom2004RequestBody {
        
        public FindSickEmployeesFrom2004RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindSickEmployeesFrom2004Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindSickEmployeesFrom2004Response", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004ResponseBody Body;
        
        public FindSickEmployeesFrom2004Response() {
        }
        
        public FindSickEmployeesFrom2004Response(ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindSickEmployeesFrom2004ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] FindSickEmployeesFrom2004Result;
        
        public FindSickEmployeesFrom2004ResponseBody() {
        }
        
        public FindSickEmployeesFrom2004ResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] FindSickEmployeesFrom2004Result) {
            this.FindSickEmployeesFrom2004Result = FindSickEmployeesFrom2004Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindMostAbsentEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindMostAbsentEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequestBody Body;
        
        public FindMostAbsentEmployeeRequest() {
        }
        
        public FindMostAbsentEmployeeRequest(ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindMostAbsentEmployeeRequestBody {
        
        public FindMostAbsentEmployeeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindMostAbsentEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindMostAbsentEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponseBody Body;
        
        public FindMostAbsentEmployeeResponse() {
        }
        
        public FindMostAbsentEmployeeResponse(ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindMostAbsentEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] FindMostAbsentEmployeeResult;
        
        public FindMostAbsentEmployeeResponseBody() {
        }
        
        public FindMostAbsentEmployeeResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] FindMostAbsentEmployeeResult) {
            this.FindMostAbsentEmployeeResult = FindMostAbsentEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTables", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllTablesRequestBody Body;
        
        public GetAllTablesRequest() {
        }
        
        public GetAllTablesRequest(ConsoleAppDebug.TUPA6Reference.GetAllTablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTablesRequestBody {
        
        public GetAllTablesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllTablesResponseBody Body;
        
        public GetAllTablesResponse() {
        }
        
        public GetAllTablesResponse(ConsoleAppDebug.TUPA6Reference.GetAllTablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllTablesResult;
        
        public GetAllTablesResponseBody() {
        }
        
        public GetAllTablesResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllTablesResult) {
            this.GetAllTablesResult = GetAllTablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeys", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllKeysRequestBody Body;
        
        public GetAllKeysRequest() {
        }
        
        public GetAllKeysRequest(ConsoleAppDebug.TUPA6Reference.GetAllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKeysRequestBody {
        
        public GetAllKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllKeysResponseBody Body;
        
        public GetAllKeysResponse() {
        }
        
        public GetAllKeysResponse(ConsoleAppDebug.TUPA6Reference.GetAllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllKeysResult;
        
        public GetAllKeysResponseBody() {
        }
        
        public GetAllKeysResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllKeysResult) {
            this.GetAllKeysResult = GetAllKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexes", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequestBody Body;
        
        public GetAllIndexesRequest() {
        }
        
        public GetAllIndexesRequest(ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllIndexesRequestBody {
        
        public GetAllIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponseBody Body;
        
        public GetAllIndexesResponse() {
        }
        
        public GetAllIndexesResponse(ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllIndexesResult;
        
        public GetAllIndexesResponseBody() {
        }
        
        public GetAllIndexesResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllIndexesResult) {
            this.GetAllIndexesResult = GetAllIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraints", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequestBody Body;
        
        public GetAllConstraintsRequest() {
        }
        
        public GetAllConstraintsRequest(ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllConstraintsRequestBody {
        
        public GetAllConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponseBody Body;
        
        public GetAllConstraintsResponse() {
        }
        
        public GetAllConstraintsResponse(ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllConstraintsResult;
        
        public GetAllConstraintsResponseBody() {
        }
        
        public GetAllConstraintsResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllConstraintsResult) {
            this.GetAllConstraintsResult = GetAllConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeeColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeeColumns", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequestBody Body;
        
        public GetAllEmployeeColumnsRequest() {
        }
        
        public GetAllEmployeeColumnsRequest(ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEmployeeColumnsRequestBody {
        
        public GetAllEmployeeColumnsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeeColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeeColumnsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponseBody Body;
        
        public GetAllEmployeeColumnsResponse() {
        }
        
        public GetAllEmployeeColumnsResponse(ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEmployeeColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllEmployeeColumnsResult;
        
        public GetAllEmployeeColumnsResponseBody() {
        }
        
        public GetAllEmployeeColumnsResponseBody(ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllEmployeeColumnsResult) {
            this.GetAllEmployeeColumnsResult = GetAllEmployeeColumnsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleAppDebug.TUPA6Reference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleAppDebug.TUPA6Reference.WebService1Soap>, ConsoleAppDebug.TUPA6Reference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetEmployeeMetaData(ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest request) {
            return base.Channel.GetEmployeeMetaData(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfString[] GetEmployeeMetaData() {
            ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequestBody();
            ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetEmployeeMetaData(inValue);
            return retVal.Body.GetEmployeeMetaDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetEmployeeMetaDataAsync(ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest request) {
            return base.Channel.GetEmployeeMetaDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataResponse> GetEmployeeMetaDataAsync() {
            ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetEmployeeMetaDataRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetEmployeeMetaDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetContentFromTable(ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest request) {
            return base.Channel.GetContentFromTable(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetContentFromTable(string tableName) {
            ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequestBody();
            inValue.Body.tableName = tableName;
            ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetContentFromTable(inValue);
            return retVal.Body.GetContentFromTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetContentFromTableAsync(ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest request) {
            return base.Channel.GetContentFromTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetContentFromTableResponse> GetContentFromTableAsync(string tableName) {
            ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetContentFromTableRequestBody();
            inValue.Body.tableName = tableName;
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetContentFromTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.InformationAboutRelatives(ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest request) {
            return base.Channel.InformationAboutRelatives(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] InformationAboutRelatives() {
            ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest inValue = new ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequestBody();
            ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).InformationAboutRelatives(inValue);
            return retVal.Body.InformationAboutRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.InformationAboutRelativesAsync(ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest request) {
            return base.Channel.InformationAboutRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesResponse> InformationAboutRelativesAsync() {
            ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest inValue = new ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.InformationAboutRelativesRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).InformationAboutRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Response ConsoleAppDebug.TUPA6Reference.WebService1Soap.FindSickEmployeesFrom2004(ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request request) {
            return base.Channel.FindSickEmployeesFrom2004(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] FindSickEmployeesFrom2004() {
            ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request inValue = new ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004RequestBody();
            ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Response retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).FindSickEmployeesFrom2004(inValue);
            return retVal.Body.FindSickEmployeesFrom2004Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Response> ConsoleAppDebug.TUPA6Reference.WebService1Soap.FindSickEmployeesFrom2004Async(ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request request) {
            return base.Channel.FindSickEmployeesFrom2004Async(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Response> FindSickEmployeesFrom2004Async() {
            ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request inValue = new ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004Request();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.FindSickEmployeesFrom2004RequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).FindSickEmployeesFrom2004Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.FindMostAbsentEmployee(ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest request) {
            return base.Channel.FindMostAbsentEmployee(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] FindMostAbsentEmployee() {
            ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest inValue = new ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequestBody();
            ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).FindMostAbsentEmployee(inValue);
            return retVal.Body.FindMostAbsentEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.FindMostAbsentEmployeeAsync(ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest request) {
            return base.Channel.FindMostAbsentEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeResponse> FindMostAbsentEmployeeAsync() {
            ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest inValue = new ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.FindMostAbsentEmployeeRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).FindMostAbsentEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.GetAllTablesResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllTables(ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest request) {
            return base.Channel.GetAllTables(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllTables() {
            ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllTablesRequestBody();
            ConsoleAppDebug.TUPA6Reference.GetAllTablesResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllTables(inValue);
            return retVal.Body.GetAllTablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllTablesResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllTablesAsync(ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest request) {
            return base.Channel.GetAllTablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllTablesResponse> GetAllTablesAsync() {
            ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllTablesRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllTablesRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllTablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.GetAllKeysResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllKeys(ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest request) {
            return base.Channel.GetAllKeys(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllKeys() {
            ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllKeysRequestBody();
            ConsoleAppDebug.TUPA6Reference.GetAllKeysResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllKeys(inValue);
            return retVal.Body.GetAllKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllKeysResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllKeysAsync(ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest request) {
            return base.Channel.GetAllKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllKeysResponse> GetAllKeysAsync() {
            ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllKeysRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllKeysRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllIndexes(ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexes(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllIndexes() {
            ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequestBody();
            ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllIndexes(inValue);
            return retVal.Body.GetAllIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllIndexesAsync(ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllIndexesResponse> GetAllIndexesAsync() {
            ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllIndexesRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllConstraints(ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraints(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllConstraints() {
            ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequestBody();
            ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllConstraints(inValue);
            return retVal.Body.GetAllConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllConstraintsAsync(ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest request) {
            return base.Channel.GetAllConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllConstraintsResponse> GetAllConstraintsAsync() {
            ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllConstraintsRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponse ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllEmployeeColumns(ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest request) {
            return base.Channel.GetAllEmployeeColumns(request);
        }
        
        public ConsoleAppDebug.TUPA6Reference.ArrayOfAnyType[] GetAllEmployeeColumns() {
            ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequestBody();
            ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponse retVal = ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllEmployeeColumns(inValue);
            return retVal.Body.GetAllEmployeeColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponse> ConsoleAppDebug.TUPA6Reference.WebService1Soap.GetAllEmployeeColumnsAsync(ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest request) {
            return base.Channel.GetAllEmployeeColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsResponse> GetAllEmployeeColumnsAsync() {
            ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest inValue = new ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequest();
            inValue.Body = new ConsoleAppDebug.TUPA6Reference.GetAllEmployeeColumnsRequestBody();
            return ((ConsoleAppDebug.TUPA6Reference.WebService1Soap)(this)).GetAllEmployeeColumnsAsync(inValue);
        }
    }
}
